module.exports = {
  // Set to true to connect with users not already in your network
  connectWithUsers: false,
  // Set to true to open the chromium browser to monitor the code
  openBrowser: false,
  // Add users to endorse
  userList: [
    // 34
    "https://www.linkedin.com/in/corneliusphanthanh/",
    "https://www.linkedin.com/in/lindawishingrad/",
    "https://www.linkedin.com/in/rachel-yoo/",
    "https://www.linkedin.com/in/sarahsong808/",
    "https://www.linkedin.com/in/spencerwyman/",
    "https://www.linkedin.com/in/andieritter",
    "https://www.linkedin.com/in/anthony-flores-8669271a3/",
    "https://www.linkedin.com/in/aris-razuri",
    "https://www.linkedin.com/in/mraustin2u/",
    "https://www.linkedin.com/in/ch-brian",
    "https://www.linkedin.com/in/ceciliayenachoi/",
    "https://www.linkedin.com/in/clarayhkim/",
    "https://www.linkedin.com/in/dakota-gilbreath/",
    "https://www.linkedin.com/in/dannyscheiner/",
    "https://www.linkedin.com/in/ibeeliot/",
    "https://www.linkedin.com/in/eamoranto",
    "https://www.linkedin.com/in/jamesmanahan/",
    "https://www.linkedin.com/in/jesse-zuniga/",
    "https://www.linkedin.com/in/jessikeecampbellwalker/",
    "https://www.linkedin.com/in/jodaisu",
    "https://www.linkedin.com/in/jdnordy/",
    "https://www.linkedin.com/in/kritikasah/",
    "https://www.linkedin.com/in/lance-jeffers/",
    "https://www.linkedin.com/in/nick-primuth-a165551a6/",
    "https://www.linkedin.com/in/noah-king",
    "https://www.linkedin.com/in/parvana-aliyeva/",
    "https://www.linkedin.com/in/saejinkang1004/",
    "https://www.linkedin.com/in/sae-min-baik",
    // 35
    "https://www.linkedin.com/in/alanlee12/",
    "https://www.linkedin.com/in/alexander-infante/",
    "https://www.linkedin.com/in/alon-ofengart/",
    "https://www.linkedin.com/in/umius-brian/",
    "https://www.linkedin.com/in/brianna-sookhoo/", 
    "https://www.linkedin.com/in/caryLchan/",
    "https://www.linkedin.com/in/cheriezhong/",
    "https://www.linkedin.com/in/christianbegor/",
    "https://www.linkedin.com/in/jaemyung/",
    "https://www.linkedin.com/in/jordan-deleon/",
    "https://www.linkedin.com/in/jphongmph/",
    "https://www.linkedin.com/in/marcus-valverde/",
    "https://www.linkedin.com/in/mike-coker/",
    "https://www.linkedin.com/in/stevefrend",
    "https://www.linkedin.com/in/shaoshen815/",
    "https://www.linkedin.com/in/toddalex/",
    "https://www.linkedin.com/in/tristenwastell/",
    "https://www.linkedin.com/in/sieunj/",
    "https://www.linkedin.com/in/vaughn-hartling-3083a4133/",
    // 36
    "https://www.linkedin.com/in/edwinmenendez/",
    "https://linkedin.com/in/cpereztoro/",
    "https://www.linkedin.com/in/nathanaelwamwenze/",
    "https://linkedin.com/in/louisxsheid/",
    "https://www.linkedin.com/in/grace-spletzer/",
    "https://www.linkedin.com/in/kattypolyak/",
    "https://www.linkedin.com/in/matthew-gin-10093679/",
    "https://www.linkedin.com/in/hideaki-aomori/",
    "https://www.linkedin.com/in/andrewjcho84/",
    "https://www.linkedin.com/in/viviancermeno/",
    "https://www.linkedin.com/in/nick-r-healy/",
    "https://www.linkedin.com/in/thomas-j-lutz/",
    "https://www.linkedin.com/in/saejinkang1004/",
    "https://www.linkedin.com/in/ronellecaguioa/",
    "https://www.linkedin.com/in/tyler-sullberg/",
    "https://www.linkedin.com/in/stephaniewood22/",
    "https://www.linkedin.com/in/akbuma/",
    "https://www.linkedin.com/in/fredochen/",
    "https://www.linkedin.com/in/michael--wang/",
    "https://www.linkedin.com/in/kate-chanthakaew/",
    "https://www.linkedin.com/in/todd-buckner/",
    "https://www.linkedin.com/in/sean-smith17",
    "https://www.linkedin.com/in/gregpanciera/",
    // 37
    "https://www.linkedin.com/in/hienqn/",
    "https://www.linkedin.com/in/migueljmiller/",
    "https://www.linkedin.com/in/kevin-fey",
    "https://www.linkedin.com/in/connorrosedelisle",
    "https://www.linkedin.com/in/steven-nguyen-t/",
    "https://www.linkedin.com/in/spenser-schwartz/",
    "https://www.linkedin.com/in/gracekiim/",
    "https://www.linkedin.com/in/john-r-madrigal/",
    "https://www.linkedin.com/in/alex-sanhueza/",
    "https://www.linkedin.com/in/justinchoo93",
    "https://www.linkedin.com/in/henrytaing/",
    "https://www.linkedin.com/in/anthony-lin/",
    "https://www.linkedin.com/in/michellebholland",
    "https://www.linkedin.com/in/s2unghobaek",
    "https://www.linkedin.com/in/cchiu2/",
    "https://www.linkedin.com/in/haejin-jo-27b212b8/",
    "https://www.linkedin.com/in/serenakuo/",
    "https://www.linkedin.com/in/nicolaspita",
    "https://www.linkedin.com/in/sean-haverstock/",
    "https://www.linkedin.com/in/jfnorton32/",
    "https://www.linkedin.com/in/mercer-stronck/",
    "https://www.linkedin.com/in/muhammadtrad/",
    "https://www.linkedin.com/in/evanberghoff/",
    "https://www.linkedin.com/in/wyatt-bell1/",
    "https://www.linkedin.com/in/jack-crish/",
    "https://www.linkedin.com/in/alanlee12/",
    "https://www.linkedin.com/in/cheriezhong/",
    "https://www.linkedin.com/in/matthew-gin-10093679/",
    "https://www.linkedin.com/in/vaughn-hartling/",
    "https://www.linkedin.com/in/stephaniewood22/",
    "https://www.linkedin.com/in/marcus-valverde/",
    "https://www.linkedin.com/in/shaoshen815/",
  ],
};
